### ISSUE TITLE
implementation in native android

### ISSUE THREAD

**Issue by nayana123** [recruit-mp/LightCalendarView#13]
Hello,
anyone has tried implementing this library in native android other than kotlin??
I am trying to set setOnStateUpdatedListener with native code

**Comment by FranciscoJavierPRamos** [comment]
Any response for this?

**Comment by recruit-mahayash** [comment]
Hi @nayana123 and @FranciscoJavierPRamos,

Sorry for our late reply.

We have added a sample implementation in Java in [Release 1.0.1](https://github.com/recruit-mp/LightCalendarView/releases/tag/1.0.1), so please refer to it. Let us know if there is anything unclear or problematic when using in Java. Feel free to reopen this issue.

Thanks!
