### ISSUE TITLE
Dot Accents not displaying correctly

### ISSUE THREAD

**Issue by Tom-Horvat** [recruit-mp/LightCalendarView#32]
Hi,

I am having trouble with dots displaying in my calendar that I present in a DialogFragment.

![screen1](https://cloud.githubusercontent.com/assets/22392962/25525439/3ee2ad12-2c0f-11e7-9950-feaeb41f8dfa.jpg)

this is what I get immediately after I open the dialog

![screen2](https://cloud.githubusercontent.com/assets/22392962/25525465/5230ade2-2c0f-11e7-97f3-ac482fb4ecbf.jpg)

and this is what happens after I swipe one month left and then back to the current month.

Both days have two dots attached to them, all different colors. On the first picture, the second dots in an array for that day are shown (partially out of frame) and when I swipe away and return to the current month the first dots are shown below the dates but slightly offset.

This happens only in my dialog fragment. When I load the calendar in a normal fragment/activity everything is fine.

This has occurred on 3 separate devices running APIs 19, 22 & 23.

**Comment by JJK-IO** [comment]
Not sure how similar this is to https://github.com/recruit-mp/LightCalendarView/issues/19

I was having issues with disappearing accent dots. Make sure each DotAccent has a unique key.
