### ISSUE TITLE
Disable color of Sunday

### ISSUE THREAD

**Issue by AriMeidan** [recruit-mp/LightCalendarView#6]
How to set Sunday as normal?

**Comment by tglovernuppy** [comment]
Hello @AriMeidan.

Thanks for your question.

Currently, we do not provide any explicit method to disable coloring Sunday or Saturday, but you can realize it by overriding color resources as follows in your app's **`/res/values/color.xml`**:

```xml
    <color name="light_calendar_view__week_day_sunday_text_color">@android:color/transparent</color>
    <color name="light_calendar_view__week_day_saturday_text_color">@android:color/transparent</color>
```

We will consider implementing a feature to customize settings for coloring individual week day if there are many requests.

Hope these help.

**Comment by hunter-isaiah96** [comment]
@AriMeidan I'd definitely like to have this functionality, it would help application designs with specific color schemes.

**Comment by recruit-mahayash** [comment]
Thanks for the requests, @AriMeidan  and @hunter-isaiah96. We will include this feature in the next release.

**Comment by recruit-mahayash** [comment]
This feature is added in [Release 1.0.1](https://github.com/recruit-mp/LightCalendarView/releases/tag/1.0.1). See [Coloring Day of The Week](https://github.com/recruit-mp/LightCalendarView/tree/1.0.1#coloring-day-of-the-week) section in README.

Thanks!
