### ISSUE TITLE
Change first day of week

### ISSUE THREAD

**Issue by franrc** [recruit-mp/LightCalendarView#9]
Hi!

It's possible to change the first day of week? I'm from Spain and here we use Monday as first day.

Greetings and congrats for your library!

**Comment by recruit-mahayash** [comment]
Hi @franrc,

Thank you for the question and the cheering message!

Currently we do not provide any way to change the first day of week, but it can be achieved by changing the line 55 in `DayLayout.kt` to something like this:

```kotlin
...
        // 左上セルの日付を計算
        cal.add(Calendar.DAY_OF_YEAR, -cal[Calendar.DAY_OF_WEEK] + 2)
        firstDate = cal.time
...
```

Still, this operation should be provided as a setting, so we will incorporate this request in the next enhancement release. We will work on this soon. 

Thank you.

**Comment by recruit-mahayash** [comment]
This feature is added in [Release 1.0.1](https://github.com/recruit-mp/LightCalendarView/releases/tag/1.0.1). Use [the added attribute](https://github.com/recruit-mp/LightCalendarView/tree/1.0.1#options) `app:lcv_firstDayOfWeek` in xml or set it programmatically.

Thanks!
